FROM node:13.12.0-alpine
WORKDIR /app
RUN npm install pm2 -g
COPY ["package.json", "package-lock.json", ".npmrc", ".env", "./"]
ENV PM2_PUBLIC_KEY 57qn2poknuk99y5
ENV PM2_SECRET_KEY aznni7gpccbbbz0
RUN npm install
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["pm2-runtime", "start", "pm2_dev.config.js"]
