# pull official base image
FROM node:13.12.0-alpine

# set working directory
WORKDIR /app

# Copies package.json and package-lock.json to Docker environment
COPY ["package.json", "package-lock.json", ".env", "./"]

# Copies everything over to Docker environment
COPY . .

# Installs all node packages
RUN npm install

RUN npm run build

# Uses port which is used by the actual application
EXPOSE 3000

CMD ["npm", "start"]
